name: mobile_app

description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  dio: ^5.9.0
  webview_flutter: ^4.8.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  mobile_scanner: ^7.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/food.png
    - assets/foto katalog/
    - assets/slices_ui/
